[build]
  functions = "netlify/functions"

# Obsługa SPA w folderze members (render z funkcji po stronie klienta)
[[redirects]]
  from = "/members"
  to = "/members/"
  status = 301

# Opcjonalnie można dodać proxy do funkcji, ale w tej wersji
# wywołujemy funkcję z JS z nagłówkiem Authorization.

# Strona 404 dla wszystkich nieznanych ścieżek
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

